{application,algos,
             [{description,[]},
              {vsn,"0.0.1"},
              {modules,[algos]},
              {registered,[]},
              {applications,[kernel
			,stdlib]},
              {mod,{algos_app,[]}},
              {env,[]}]}.
